---
default_stages: [commit, push]
minimum_pre_commit_version: "1.20.0"
default_language_version:
  python: python3.8
repos:
- repo: https://github.com/pre-commit/pre-commit-hooks
  rev: v3.2.0
  hooks:
    - id: trailing-whitespace
    - id: end-of-file-fixer
    - id: check-yaml
    - id: check-added-large-files
- repo: https://github.com/psf/black
  rev: 22.10.0
  hooks:
    - id: black
      args: [--config=./pyproject.toml]
- repo: https://github.com/pycqa/flake8
  rev: 4.0.1
  hooks:
    - id: flake8
      args: [--max-line-length=131, --exclude=docker/test_app/*, --exclude=tests/*]
