site_name: Testcompose
site_description: A lightweight  docker library for writing integration tests in Python.
site_url: https://rugging24.github.io/python-testcompose/

repo_url: https://github.com/rugging24/python-testcompose
repo_name: rugging24/python-testcompose
edit_uri: ""

theme:
  name: material
  palette:
    scheme: default
    primary: brown
    accent: amber
  icon:
    repo: fontawesome/brands/github
  font:
    text: Roboto
    code: Roboto Mono

plugins:
  - git-revision-date
  - autorefs
  - search
  - mkdocstrings:
      handlers:
        python:
          selection:
            filters:
              - "!^_"
          rendering:
            show_root_heading: true
            show_source: true
            show_root_full_path: true
            show_object_full_path: false
            show_if_no_docstring: true
            show_signature_annotations: true
            show_root_members_full_path: false
            show_category_heading: false # shows the modules, classes , methods e.t.c
            show_bases: true
            setup_commands:
                - import sys, os
                - sys.path.insert(0, os.path.abspath('..'))
            selection:
                new_path_syntax: true
                inherited_members: true
      watch:
        - testcompose


markdown_extensions:
  - admonition
  - codehilite
  - markdown.extensions.admonition
  - markdown.extensions.attr_list
  - markdown.extensions.def_list
  - markdown.extensions.footnotes
  - markdown.extensions.meta


nav:
  - Introduction: 'index.md'
  - QuickStart: 'quickstart.md'
  - Environment Variables: 'environment_variables.md'
  - Developer Reference: 'api.md'

extra_css:
  - css/custom.css
