name: DeployDoc
on:
  workflow_run:
    workflows:
      - Tests
    branches:
      - main
    types:
      - completed
jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Build and Publish to PyPI/Github Pages"
        run: "scripts/build-and-publish-packages.sh"
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_TOKEN }}
