name: DeployDoc
on:
  workflow_run:
    workflows:
      - RunTests
    branches:
      - main
    types:
      - completed
jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - name: "Build and Publish to PyPI/Github Pages"
        run: "scripts/build-and-publish-packages.sh"
      - name: "Build doc"
        run: mkdocs build
      - name: "deploy doc"
        run: mkdocs gh-deploy --force
      - name: "build package"
        run: python setup.py sdist bdist_wheel && twine check dist/* && twine upload dist/*
        env:
          TWINE_USERNAME: __token__
          TWINE_PASSWORD: ${{ secrets.PYPI_TWINE_TOKEN }}
