name: DeployDoc
on:
  workflow_run:
    workflows:
      - RunTests
    branches:
      - main
    types:
      - completed
jobs:
  deploy-doc:
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-python@v2
        with:
          python-version: 3.9
      - run: pip install mkdocs-material mkdocs-git-revision-date-plugin mkdocs-material mkdocs-material-extensions mkdocstrings mkdocs-autorefs mkdocs markdown markupsafe
      - run: mkdocs gh-deploy --force
