name: DeployDoc
on:
  workflow_run:
    workflows:
      - Tests
    branches:
      - main
    types:
      - completed
jobs:
  deploy-doc:
    environment: release
    permissions:
      id-token: write
    runs-on: ubuntu-latest
    if: ${{ github.event.workflow_run.conclusion == 'success' }}
    steps:
      - uses: actions/checkout@v3
      - run: git fetch --prune --unshallow
      - uses: actions/setup-python@v4
        with:
          python-version: "3.11"
      - name: Setup Poetry
        uses: abatilo/actions-poetry@v2
        with:
          poetry-version: "1.6.1"
      - name: Build package
        run: |
          poetry install --no-root
          bash -x scripts/create_version.sh
          poetry build
      - uses: pypa/gh-action-pypi-publish@release/v1
      - name: "Publish to PyPI & Github Pages"
        run: |
          poetry run twine check dist/*
          poetry run mkdocs build
          poetry publish
          poetry run mkdocs gh-deploy --force
