name: RunningTests
on: [push]
jobs:
  tests:
    name: "Tests - Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.7'
          # - '3.8'
          # - '3.9'
          # - '3.10'
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests in ${{ matrix.python-version }} Environments
        env:
          PY_VERSION: ${{ matrix.python-version }}
        run: "scripts/run-tests.sh ${{ matrix.python-version }}"
