name: SnykScanner
on: [push]
jobs:
  security:
    name: Snyk Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=upgradable  --fail-on=patchable --show-vulnerable-paths==all --prune-repeated-subdependencies
