name: Tests
on: [push]
jobs:
  security:
    name: Snyk Security Scanner
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - name: Run Snyk to check for vulnerabilities
        uses: snyk/actions/python@master
        env:
          SNYK_TOKEN: ${{ secrets.SNYK_TOKEN }}
        with:
          args: --fail-on=upgradable  --fail-on=patchable --show-vulnerable-paths=all --prune-repeated-subdependencies
  tests:
    name: "Tests - Python ${{ matrix.python-version }}"
    runs-on: ${{ matrix.os }}
    strategy:
      max-parallel: 1
      matrix:
        os:
          - ubuntu-latest
        python-version:
          - '3.7'
          - '3.8'
          - '3.9'
          - '3.10'
          - '3.11'
    steps:
      - name: Code Checkout
        uses: actions/checkout@v2
      - name: Set up Python
        uses: actions/setup-python@v2
        with:
          python-version: ${{ matrix.python-version }}
      - name: Run Tests in ${{ matrix.python-version }} Environments
        env:
          PY_VERSION: ${{ matrix.python-version }}
        run: "scripts/run-tests.sh ${{ matrix.python-version }}"
